version: "3.7"

services:
  database_queries_ignite:
    image: postgres
    container_name: database_queries_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: queries_challenge
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_queries_ignite
    depends_on: 
      - database_queries_ignite

volumes:
  pgdata:
    driver: local